(define (even? x) (= (remainder x 2) 0))
(define (inc x) (+ x 1))

(define (simp-integral f a b n)
  (define h (/ (- b a) n))
  (define (arg term) (+ a (* term h)))
  (define (simp-rule term)
    (cond ((or (= term 0) (= term n)) (f (arg term)))
          ((even? term) (* 2 (f (arg term))))
          (else (* 4 (f (arg term))))
    )
  )
  (* (/ h 3) (sum a b simp-rule inc))
)
