(define (even? x) (= (remainder x 2) 0))
(define (inc x) (+ x 1))
(define (cube x) (* x x x))
(define (iden x) x)

(define (integral f a b dx)
  (define (add-dx x) (+ x dx))
  (* (sum (+ a (/ dx 2.0)) b f add-dx) dx)
)

(define (sum from to apply next)
  (if (> from to)
      0
      (+ (apply from) (sum (next from) to apply next))
  )
)

(define (simp-integral f a b n)
  (define h (/ (- b a) n))
  (define (arg term) (+ a (* term h)))
  (define (simp-rule term)
    (cond ((or (= term 0) (= term n)) (f (arg term)))
          ((even? term) (* 2.0 (f (arg term))))
          (else (* 4.0 (f (arg term))))
    )
  )
  (* (/ h 3.0) (sum a n simp-rule inc))
)

(sum 1 10 iden inc)
(integral cube 0 1 0.0001)
(integral cube 0 1 0.00001)
(simp-integral cube 0 1 1)
(simp-integral cube 0 1 10)
(simp-integral cube 0 1 100)
(simp-integral cube 0 1 1000)
(simp-integral cube 0 1 10000)
(simp-integral cube 0 1 100000)
